grid:
    id: system-emails
    headerEnabled: yes
    type: html
    pagination:
        pageSize: 20
    columns:
        id:
            order: id
            label: id
            title: id
            type: text
            content: {{id}}
        code:
            label: code
            title: code
            type: text
            content: {{code}}
        from:
            type: text
            label: from
            title: from
            content: {{locale.fromName}} &lt;{{from}}&gt;
        subject:
            type: text
            label: subject
            title: subject
            content: {{locale.subject:|cat%50%word%dots}}
        contentType:
            type: text
            label: content_type
            title: content_type
            content: {{contentType}}
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit
                    url:
                        module: system
                        controller: email-templates
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: email-templates
                        action: delete
                        id: {{id}}