grid:
    id: system-languages
    headerEnabled: yes
    type: html
    pagination:
        pageSize: 20
    columns:
        id:
            order: id
            label: id
            title: id
            type: text
            content: {{id}}
        name:
            label: name
            title: name
            type: text
            content: {{name}}
        locale:
            type: text
            label: locale
            title: locale
            content: {{locale}}
        isAvailable:
            type: checkbox
            label: is_available
            title: is_available
            content: isAvailable
            valueChecked: yes
            valueUnchecked: no
            disabled: true
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit fancybox-edit fancybox.ajax
                    url:
                        module: system
                        controller: languages
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: languages
                        action: delete
                        id: {{id}}