grid:
    id: photos
    headerEnabled: yes
    type: html
    defaultOrdering: rank
    pagination:
        pageSize: 80
    rowData:
        id: id
    columns:
        drag:
            type: drag
        id:
            label: id
            title: id
            type: text
            content: {{id}}
        title:
            label: title
            title: title
            type: text
            content: {{title}}
        image:
            label: image
            title: image
            type: image
            content: imageThumb
            style: height:50px
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit fancybox-edit fancybox.ajax
                    url:
                        module: system
                        controller: about
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: about
                        action: delete
                        id: {{id}}