<div id="about-us">
    <div class="promo">
        <div class="promo-img">
            <?php foreach($this->photos as $key => $photo): ?>
            <a rel="fancybox-thumb" style="display:none;" href="<?php echo $photo->imageLarge?>" class="fancyshow num-<?php echo strval($key)?>">
                <img src="" alt="<?php echo addslashes($photo->title)?>" title="<?php echo addslashes($photo->title)?>" />
            </a>
            <?php endforeach ?>
        </div>
        <div class="promo-text about_text">
            <h2></h2>
            <p>

            </p>
        </div>
    </div>
    <div class="gallery">
        <a href="javascript:void(0)" class="prev"></a>
        <div class="list-holder" style="width:860px;">
            <ul class="bottom-slider">
                <?php foreach($this->photos as $key => $photo): ?>
                    <li data-image="<?php echo $photo->image?>" data-slide="num-<?php echo strval($key)?>">
                        <img src="<?php echo $photo->imageThumb?>" alt="<?php echo addslashes($photo->title)?>" />
                        <a href="javascript:viod(0)"></a>
                        <div style="display:none;" class="description-holder">
                            <?php echo nl2br($photo->description) ?>
                        </div>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
        <a href="avascript:void(0)" class="next"></a>
    </div>
</div>