grid:
    id: system-acl-groups
    headerEnabled: yes
    type: html
    pagination:
        pageSize: 20
    columns:
        id:
            order: id
            label: id
            title: id
            type: text
            content: {{id}}
        name:
            label: name
            title: name
            type: text
            content: {{name}}
        lastLogin:
            order: code
            label: code
            title: code
            type: text
            content: {{code}}
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit fancybox-edit fancybox.ajax
                    url:
                        module: system
                        controller: acl-groups
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: acl-groups
                        action: delete
                        id: {{id}}