<div>
    <?php if($this->addAction != null):?>
        <div class="top-button-container">
            <?php
            /** @var Core_View_Helper_ActionHref $actionHref  */
            echo $this->actionHref()
                ->setUrl(array('action' => 'create',))
                ->setClass('btn btn-success fancybox-edit fancybox.ajax')
                ->setLabel($this->addAction)
                ->setTitle($this->addAction);
            ?>
        </div>
    <?php endif;?>
    <h3><?php echo $this->translate($this->caption)?></h3>
    <?php echo $this->grid->renderGrid()?>
</div>
<script type="text/javascript">
    $('#grid_team table tbody').sortable({
        axis: 'y',
        handle: '.drag-handler',
        update:function()
        {
            var data = new Object();
            $('#grid_team table tbody tr').each(function(index){
                data[$(this).data('id')] = index;
            });
            console.log(data);
            $.ajax({
                url:'<?php echo $this->url(array('action' => 'reorder-items'))?>',
                type:'POST',
                data:{
                    'items':data
                }
            });
        }
    });
</script>