grid:
    id: static-pages
    headerEnabled: yes
    type: html
    pagination:
        pageSize: 20
    columns:
        id:
            order: id
            label: id
            title: id
            type: text
            content: {{id}}
        code:
            label: code
            title: code
            type: text
            content: {{code}}
        title:
            label: title
            title: title
            type: text
            content: {{locale.title}}
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit
                    url:
                        module: system
                        controller: static-pages
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: static-pages
                        action: delete
                        id: {{id}}