grid:
    id: clinic-photos
    headerEnabled: yes
    type: html
    pagination:
        pageSize: 80
    rowData:
        id: id
    defaultOrdering: rank
    columns:
        drag:
            type: drag
        id:
            order: id
            label: id
            title: id
            type: text
            content: {{id}}
        title:
            type: text
            label: title
            title: title
            content: {{title}}
        isEnabled:
            type: checkbox
            label: is_enabled
            title: is_enabled
            content: isEnabled
            valueChecked: yes
            valueUnchecked: no
            disabled: true
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                gallery:
                    title: action_gallery
                    htmlAttributes:
                        class: icon-picture
                    url:
                        module: system
                        controller: clinic-cases-gallery
                        action: index
                        case-id: {{id}}
                        return-to: false
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit fancybox-edit fancybox.ajax
                    url:
                        module: system
                        controller: clinic-cases
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: clinic-cases
                        action: delete
                        id: {{id}}