grid:
    id: clinic-photos
    headerEnabled: yes
    type: html
    defaultOrdering: rank
    pagination:
        pageSize: 80
    rowData:
        id: id
    columns:
        drag:
            type: drag
        id:
            label: id
            title: id
            type: text
            content: {{id}}
        description:
            label: description
            title: description
            type: text
            content: {{description:|cat%50%word%dots}}
        isCover:
            type: checkbox
            label: is_cover
            title: is_cover
            content: isCover
            valueChecked: yes
            valueUnchecked: no
            disabled: true
        image:
            label: image
            title: image
            type: image
            content: imageThumb
            style: height:50px
        actions:
            type: actions
            splitter: &nbsp;&nbsp;
            content:
                edit:
                    title: action_edit
                    htmlAttributes:
                        class: icon-edit fancybox-edit fancybox.ajax
                    url:
                        module: system
                        controller: clinic-cases-gallery
                        action: edit
                        id: {{id}}
                delete:
                    title: action_delete
                    htmlAttributes:
                        class: icon-remove-circle
                    confirm: delete_confirmation
                    url:
                        module: system
                        controller: clinic-cases-gallery
                        action: delete
                        id: {{id}}