<div class="content">
    <ul class="menu">
        <?php foreach($this->articles as $article):?>
            <li><!--class="active"-->
                <a href="<?php echo '#'.$article->code?>">
                    <?php echo $article->title?>
                </a>
            </li>
        <?php endforeach;?>
    </ul>
    <div class="main">
        <?php foreach($this->articles as $article):?>
            <div class="article" id="<?php echo $article->code?>">
                <h3 style="cursor:pointer" onclick="location.href='/publication/<?php echo $article->code?>'"><?php echo $article->title?></h3>
                <div class="article-holder">
                    <?php if($article->image != ''):?>
                        <img src="<?php echo $article->image?>" alt="<?php echo addslashes($article->title);?>" />
                    <?php endif;?>
                    <?php
                        $content = $article->content;
                        $content = str_replace('<br>', "\r\n", $content);
                        $content = str_replace('<br />', "\r\n", $content);
                        $content = str_replace('</p>', "\r\n", $content);
                        $content = strip_tags($content);
                        if(strlen($content) > 2000)
                        {
                            $pos = strpos($content, '.',2000);
                            if(!$pos)
                            {
                                $pos = strpos($content, ',',2000);
                            }
                            if(!$pos)
                            {
                                $pos = strpos($content, ' ',2000);
                            }
                            if($pos != false)
                            {
                                $content = nl2br(substr($content, 0, $pos));
                                $content .= ' ...';
                            }
                        }
                    ?>
                    <p>
                        <?php echo $content;?>
                    </p>
                </div>
                <div class="ref"><a href="/publication/<?php echo $article->code?>">Развернуть статью</a></div>
            </div>
        <?php endforeach;?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('ul.menu li a').click(function(){
            var scrollTo = $(this).attr('href').split('#');
            scrollTo = scrollTo[1];
            $(document.body).scrollTo('#'+scrollTo, 500);
            localtion.hash = scrollTo;
            return false;
        });
    })
</script>